// Translations for the memory_boost module.
// Keys: '<module>.<name>'. Languages: en, hi, hinglish, te, ta, pa, bho, mr, sa.
// Each entry must have at least 'en'. Placeholders like {name} are filled by tr().
const Map<String, Map<String, String>> memoryBoostStrings = {
  // ---- Brain Gym menu
  'memory_boost.title': {'en': "Brain Gym", 'hi': "ब्रेन जिम", 'hinglish': "Brain Gym", 'te': "బ్రెయిన్ జిమ్", 'ta': "மூளை பயிற்சி", 'pa': "ਬ੍ਰੇਨ ਜਿਮ", 'bho': "दिमाग के कसरत", 'mr': "मेंदू व्यायामशाळा", 'sa': "मस्तिष्क-व्यायामशाला"},
  'memory_boost.card.title': {'en': "Card Match", 'hi': "कार्ड मिलान", 'hinglish': "Card Match", 'te': "కార్డ్ మ్యాచ్", 'ta': "அட்டை பொருத்தம்", 'pa': "ਕਾਰਡ ਮੇਲ", 'bho': "कार्ड मिलान", 'mr': "पत्ते जुळवा", 'sa': "पत्र-मेलनम्"},
  'memory_boost.card.sub': {'en': "Flip pairs of cards. Easy to Extreme.", 'hi': "कार्ड पलटकर जोड़े ढूंढें। आसान से बहुत कठिन तक।", 'hinglish': "Cards palto, jodi dhoondo. Easy se Extreme tak.", 'te': "కార్డులు తిప్పి జతలు కనుగొను. సులభం నుండి అతి కఠినం వరకు.", 'ta': "அட்டைகளைத் திருப்பி ஜோடிகளைக் கண்டுபிடி. எளிது முதல் மிகக் கடினம் வரை.", 'pa': "ਕਾਰਡ ਪਲਟੋ, ਜੋੜੇ ਲੱਭੋ। ਆਸਾਨ ਤੋਂ ਬਹੁਤ ਔਖਾ ਤੱਕ।", 'bho': "कार्ड पलटीं, जोड़ा खोजीं। आसान से बहुत कठिन ले।", 'mr': "पत्ते उलटून जोड्या शोधा. सोप्यापासून अतिकठीणपर्यंत.", 'sa': "पत्राणि परिवर्त्य युग्मानि अन्विष्यत। सरलात् अतिकठिनपर्यन्तम्।"},
  'memory_boost.card.stars': {'en': "Stars {n}/{max}", 'hi': "सितारे {n}/{max}", 'hinglish': "Stars {n}/{max}", 'te': "నక్షత్రాలు {n}/{max}", 'ta': "நட்சத்திரங்கள் {n}/{max}", 'pa': "ਤਾਰੇ {n}/{max}", 'bho': "तारा {n}/{max}", 'mr': "तारे {n}/{max}", 'sa': "तारकाः {n}/{max}"},
  'memory_boost.simon.title': {'en': "Simon Sequence", 'hi': "साइमन क्रम", 'hinglish': "Simon Sequence", 'te': "సైమన్ క్రమం", 'ta': "சைமன் வரிசை", 'pa': "ਸਾਇਮਨ ਕ੍ਰਮ", 'bho': "साइमन क्रम", 'mr': "सायमन क्रम", 'sa': "सायमन-क्रमः"},
  'memory_boost.simon.short': {'en': "Simon", 'hi': "साइमन", 'hinglish': "Simon", 'te': "సైమన్", 'ta': "சைமன்", 'pa': "ਸਾਇਮਨ", 'bho': "साइमन", 'mr': "सायमन", 'sa': "सायमन"},
  'memory_boost.simon.sub': {'en': "Repeat the growing light pattern.", 'hi': "बढ़ते रोशनी पैटर्न को दोहराएं।", 'hinglish': "Badhta light pattern repeat karo.", 'te': "పెరుగుతున్న లైట్ నమూనాను మళ్లీ చేయి.", 'ta': "வளரும் ஒளி வரிசையைத் திரும்பச் செய்.", 'pa': "ਵਧਦੇ ਰੌਸ਼ਨੀ ਪੈਟਰਨ ਨੂੰ ਦੁਹਰਾਓ।", 'bho': "बढ़त रोसनी के पैटर्न दोहराईं।", 'mr': "वाढत जाणारा प्रकाश क्रम पुन्हा करा.", 'sa': "वर्धमानं प्रकाशक्रमं पुनः कुरुत।"},
  'memory_boost.simon.best_streak': {'en': "Best streak {n}", 'hi': "सर्वश्रेष्ठ लगातार {n}", 'hinglish': "Best streak {n}", 'te': "ఉత్తమ వరుస {n}", 'ta': "சிறந்த தொடர் {n}", 'pa': "ਸਭ ਤੋਂ ਵਧੀਆ ਲੜੀ {n}", 'bho': "सबसे बढ़िया लगातार {n}", 'mr': "सर्वोत्तम सलग {n}", 'sa': "श्रेष्ठः अनुक्रमः {n}"},
  'memory_boost.number.title': {'en': "Number Memory", 'hi': "नंबर याददाश्त", 'hinglish': "Number Memory", 'te': "సంఖ్య జ్ఞాపకం", 'ta': "எண் நினைவு", 'pa': "ਨੰਬਰ ਯਾਦਦਾਸ਼ਤ", 'bho': "नंबर याद", 'mr': "अंक स्मृती", 'sa': "संख्यास्मृतिः"},
  'memory_boost.number.short': {'en': "Number", 'hi': "नंबर", 'hinglish': "Number", 'te': "సంఖ్య", 'ta': "எண்", 'pa': "ਨੰਬਰ", 'bho': "नंबर", 'mr': "अंक", 'sa': "संख्या"},
  'memory_boost.number.sub': {'en': "Remember the number, one more digit each round.", 'hi': "नंबर याद रखें, हर राउंड एक अंक और।", 'hinglish': "Number yaad rakho, har round ek digit aur.", 'te': "సంఖ్యను గుర్తుంచుకో, ప్రతి రౌండ్‌కు ఒక అంకె ఎక్కువ.", 'ta': "எண்ணை நினைவில் வை, ஒவ்வொரு சுற்றிலும் ஒரு இலக்கம் கூடும்.", 'pa': "ਨੰਬਰ ਯਾਦ ਰੱਖੋ, ਹਰ ਰਾਊਂਡ ਇੱਕ ਅੰਕ ਹੋਰ।", 'bho': "नंबर याद राखीं, हर राउंड में एगो अंक अउर।", 'mr': "संख्या लक्षात ठेवा, प्रत्येक फेरीत एक अंक जास्त.", 'sa': "संख्यां स्मरत, प्रतिचरणम् एकः अङ्कः अधिकः।"},
  'memory_boost.number.best_round': {'en': "Best round {n}", 'hi': "सर्वश्रेष्ठ राउंड {n}", 'hinglish': "Best round {n}", 'te': "ఉత్తమ రౌండ్ {n}", 'ta': "சிறந்த சுற்று {n}", 'pa': "ਸਭ ਤੋਂ ਵਧੀਆ ਰਾਊਂਡ {n}", 'bho': "सबसे बढ़िया राउंड {n}", 'mr': "सर्वोत्तम फेरी {n}", 'sa': "श्रेष्ठं चरणम् {n}"},

  // ---- Shared
  'memory_boost.last': {'en': "LAST", 'hi': "पिछला", 'hinglish': "LAST", 'te': "చివరిది", 'ta': "கடைசி", 'pa': "ਪਿਛਲਾ", 'bho': "पिछला", 'mr': "मागील", 'sa': "पूर्वतनम्"},
  'memory_boost.moves_n': {'en': "{n} moves", 'hi': "{n} चालें", 'hinglish': "{n} moves", 'te': "{n} కదలికలు", 'ta': "{n} நகர்வுகள்", 'pa': "{n} ਚਾਲਾਂ", 'bho': "{n} चाल", 'mr': "{n} चाली", 'sa': "{n} चालाः"},
  'memory_boost.new_best': {'en': "New best!", 'hi': "नया रिकॉर्ड!", 'hinglish': "Naya record!", 'te': "కొత్త రికార్డ్!", 'ta': "புதிய சாதனை!", 'pa': "ਨਵਾਂ ਰਿਕਾਰਡ!", 'bho': "नया रिकॉर्ड!", 'mr': "नवीन विक्रम!", 'sa': "नूतनः अभिलेखः!"},
  'memory_boost.best_value': {'en': "Best: {n}", 'hi': "सर्वश्रेष्ठ: {n}", 'hinglish': "Best: {n}", 'te': "ఉత్తమం: {n}", 'ta': "சிறந்தது: {n}", 'pa': "ਸਭ ਤੋਂ ਵਧੀਆ: {n}", 'bho': "सबसे बढ़िया: {n}", 'mr': "सर्वोत्तम: {n}", 'sa': "श्रेष्ठम्: {n}"},
  'memory_boost.time_up': {'en': "Time is up!", 'hi': "समय खत्म!", 'hinglish': "Time khatam!", 'te': "సమయం అయిపోయింది!", 'ta': "நேரம் முடிந்தது!", 'pa': "ਸਮਾਂ ਖਤਮ!", 'bho': "समय खतम!", 'mr': "वेळ संपली!", 'sa': "समयः समाप्तः!"},
  'memory_boost.start': {'en': "Start", 'hi': "शुरू करें", 'hinglish': "Start", 'te': "ప్రారంభించు", 'ta': "தொடங்கு", 'pa': "ਸ਼ੁਰੂ ਕਰੋ", 'bho': "शुरू करीं", 'mr': "सुरू करा", 'sa': "आरभध्वम्"},
  'memory_boost.seconds': {'en': "{n}s", 'hi': "{n} सेकंड", 'hinglish': "{n}s", 'te': "{n} సె", 'ta': "{n} வி", 'pa': "{n} ਸਕਿੰਟ", 'bho': "{n} सेकेंड", 'mr': "{n} सेकंद", 'sa': "{n} क्षणाः"},

  // ---- Card Match
  'memory_boost.card.heading': {'en': "Flip pairs of cards and find every match. Pick a difficulty.", 'hi': "कार्ड पलटें और हर जोड़ा ढूंढें। कठिनाई चुनें।", 'hinglish': "Cards palto aur har jodi dhoondo. Difficulty chuno.", 'te': "కార్డులు తిప్పి ప్రతి జతను కనుగొను. కష్టస్థాయి ఎంచుకో.", 'ta': "அட்டைகளைத் திருப்பி எல்லா ஜோடிகளையும் கண்டுபிடி. கடினநிலையைத் தேர்வு செய்.", 'pa': "ਕਾਰਡ ਪਲਟੋ ਅਤੇ ਹਰ ਜੋੜਾ ਲੱਭੋ। ਮੁਸ਼ਕਲ ਚੁਣੋ।", 'bho': "कार्ड पलटीं आ हर जोड़ा खोजीं। कठिनाई चुनीं।", 'mr': "पत्ते उलटा आणि प्रत्येक जोडी शोधा. काठिण्य निवडा.", 'sa': "पत्राणि परिवर्तयत, सर्वाणि युग्मानि अन्विष्यत। काठिन्यं चिनुत।"},
  'memory_boost.card.desc.easy': {'en': "2x2 to 4x4. Mismatches stay visible a long time.", 'hi': "2x2 से 4x4। गलत जोड़े देर तक दिखते हैं।", 'hinglish': "2x2 se 4x4. Galat jodi der tak dikhti hai.", 'te': "2x2 నుండి 4x4. తప్పు జతలు చాలా సేపు కనిపిస్తాయి.", 'ta': "2x2 முதல் 4x4. தவறான ஜோடிகள் நீண்ட நேரம் தெரியும்.", 'pa': "2x2 ਤੋਂ 4x4। ਗਲਤ ਜੋੜੇ ਦੇਰ ਤੱਕ ਦਿਖਦੇ ਹਨ।", 'bho': "2x2 से 4x4। गलत जोड़ा देर ले देखाई देला।", 'mr': "2x2 ते 4x4. चुकीच्या जोड्या बराच वेळ दिसतात.", 'sa': "2x2 तः 4x4 पर्यन्तम्। अयुक्तयुग्मानि चिरं दृश्यन्ते।"},
  'memory_boost.card.desc.medium': {'en': "2x2 to 6x6. Balanced flip-back time.", 'hi': "2x2 से 6x6। संतुलित पलटने का समय।", 'hinglish': "2x2 se 6x6. Balanced flip-back time.", 'te': "2x2 నుండి 6x6. సమతుల్య తిరిగి తిప్పే సమయం.", 'ta': "2x2 முதல் 6x6. சமநிலையான திருப்பும் நேரம்.", 'pa': "2x2 ਤੋਂ 6x6। ਸੰਤੁਲਿਤ ਪਲਟਣ ਦਾ ਸਮਾਂ।", 'bho': "2x2 से 6x6। ठीक-ठाक पलटे के समय।", 'mr': "2x2 ते 6x6. संतुलित उलटण्याचा वेळ.", 'sa': "2x2 तः 6x6 पर्यन्तम्। सन्तुलितः परिवर्तनसमयः।"},
  'memory_boost.card.desc.hard': {'en': "3x4 to 5x6. Cards flip back fast.", 'hi': "3x4 से 5x6। कार्ड जल्दी पलट जाते हैं।", 'hinglish': "3x4 se 5x6. Cards jaldi palat jaate hain.", 'te': "3x4 నుండి 5x6. కార్డులు వేగంగా తిరిగి తిరుగుతాయి.", 'ta': "3x4 முதல் 5x6. அட்டைகள் வேகமாகத் திரும்பும்.", 'pa': "3x4 ਤੋਂ 5x6। ਕਾਰਡ ਜਲਦੀ ਪਲਟ ਜਾਂਦੇ ਹਨ।", 'bho': "3x4 से 5x6। कार्ड जल्दी पलट जाला।", 'mr': "3x4 ते 5x6. पत्ते पटकन उलटतात.", 'sa': "3x4 तः 5x6 पर्यन्तम्। पत्राणि शीघ्रं परिवर्तन्ते।"},
  'memory_boost.card.desc.extreme': {'en': "5x6 and 6x6. Short peek, very fast flip-back, time limit.", 'hi': "5x6 और 6x6। छोटी झलक, बहुत तेज़ पलटना, समय सीमा।", 'hinglish': "5x6 aur 6x6. Chhoti jhalak, bahut fast flip, time limit.", 'te': "5x6 మరియు 6x6. చిన్న చూపు, చాలా వేగంగా తిప్పడం, సమయ పరిమితి.", 'ta': "5x6 மற்றும் 6x6. குறுகிய பார்வை, மிக வேகமான திருப்பம், நேர வரம்பு.", 'pa': "5x6 ਅਤੇ 6x6। ਛੋਟੀ ਝਲਕ, ਬਹੁਤ ਤੇਜ਼ ਪਲਟਣਾ, ਸਮਾਂ ਸੀਮਾ।", 'bho': "5x6 आ 6x6। छोट झलक, बहुत तेज पलटल, समय के सीमा।", 'mr': "5x6 आणि 6x6. छोटी झलक, खूप जलद उलटणे, वेळेची मर्यादा.", 'sa': "5x6 6x6 च। अल्पं दर्शनम्, अतिशीघ्रं परिवर्तनम्, समयसीमा।"},
  'memory_boost.card.grid': {'en': "{grid} grid", 'hi': "{grid} ग्रिड", 'hinglish': "{grid} grid", 'te': "{grid} గ్రిడ్", 'ta': "{grid} கட்டம்", 'pa': "{grid} ਗ੍ਰਿਡ", 'bho': "{grid} ग्रिड", 'mr': "{grid} ग्रिड", 'sa': "{grid} जालम्"},
  'memory_boost.card.not_played': {'en': "Not played yet", 'hi': "अभी खेला नहीं", 'hinglish': "Abhi khela nahi", 'te': "ఇంకా ఆడలేదు", 'ta': "இன்னும் விளையாடவில்லை", 'pa': "ਹਾਲੇ ਖੇਡਿਆ ਨਹੀਂ", 'bho': "अबहीं ना खेलल गइल", 'mr': "अजून खेळले नाही", 'sa': "अद्यापि न क्रीडितम्"},
  'memory_boost.card.best_moves': {'en': "Best: {n} moves", 'hi': "सर्वश्रेष्ठ: {n} चालें", 'hinglish': "Best: {n} moves", 'te': "ఉత్తమం: {n} కదలికలు", 'ta': "சிறந்தது: {n} நகர்வுகள்", 'pa': "ਸਭ ਤੋਂ ਵਧੀਆ: {n} ਚਾਲਾਂ", 'bho': "सबसे बढ़िया: {n} चाल", 'mr': "सर्वोत्तम: {n} चाली", 'sa': "श्रेष्ठम्: {n} चालाः"},
  'memory_boost.card.pairs_found': {'en': "{n}/{total} pairs found", 'hi': "{n}/{total} जोड़े मिले", 'hinglish': "{n}/{total} jodi mili", 'te': "{n}/{total} జతలు దొరికాయి", 'ta': "{n}/{total} ஜோடிகள் கிடைத்தன", 'pa': "{n}/{total} ਜੋੜੇ ਲੱਭੇ", 'bho': "{n}/{total} जोड़ा मिलल", 'mr': "{n}/{total} जोड्या सापडल्या", 'sa': "{n}/{total} युग्मानि लब्धानि"},
  'memory_boost.card.peek_free': {'en': "Peek  (1 free)", 'hi': "झलक  (1 मुफ़्त)", 'hinglish': "Peek  (1 free)", 'te': "చూడు  (1 ఉచితం)", 'ta': "பார்  (1 இலவசம்)", 'pa': "ਝਲਕ  (1 ਮੁਫ਼ਤ)", 'bho': "झलक  (1 फ्री)", 'mr': "झलक  (1 मोफत)", 'sa': "ईक्षा  (1 मुक्तम्)"},
  'memory_boost.card.peek_coins': {'en': "Peek  ({n} coins)", 'hi': "झलक  ({n} सिक्के)", 'hinglish': "Peek  ({n} coins)", 'te': "చూడు  ({n} నాణేలు)", 'ta': "பார்  ({n} நாணயங்கள்)", 'pa': "ਝਲਕ  ({n} ਸਿੱਕੇ)", 'bho': "झलक  ({n} सिक्का)", 'mr': "झलक  ({n} नाणी)", 'sa': "ईक्षा  ({n} मुद्राः)"},

  // ---- Simon
  'memory_boost.simon.heading': {'en': "Watch the growing light pattern and repeat it. Pick a difficulty.", 'hi': "बढ़ता रोशनी पैटर्न देखें और दोहराएं। कठिनाई चुनें।", 'hinglish': "Badhta light pattern dekho aur repeat karo. Difficulty chuno.", 'te': "పెరుగుతున్న లైట్ నమూనా చూసి మళ్లీ చేయి. కష్టస్థాయి ఎంచుకో.", 'ta': "வளரும் ஒளி வரிசையைப் பார்த்துத் திரும்பச் செய். கடினநிலையைத் தேர்வு செய்.", 'pa': "ਵਧਦਾ ਰੌਸ਼ਨੀ ਪੈਟਰਨ ਦੇਖੋ ਅਤੇ ਦੁਹਰਾਓ। ਮੁਸ਼ਕਲ ਚੁਣੋ।", 'bho': "बढ़त रोसनी के पैटर्न देखीं आ दोहराईं। कठिनाई चुनीं।", 'mr': "वाढत जाणारा प्रकाश क्रम पाहा आणि पुन्हा करा. काठिण्य निवडा.", 'sa': "वर्धमानं प्रकाशक्रमं पश्यत, पुनः कुरुत च। काठिन्यं चिनुत।"},
  'memory_boost.simon.desc.easy': {'en': "Slow lights, 4 pads, one forgiven mistake.", 'hi': "धीमी रोशनी, 4 पैड, एक गलती माफ़।", 'hinglish': "Slow lights, 4 pads, ek galti maaf.", 'te': "నెమ్మదిగా లైట్లు, 4 ప్యాడ్లు, ఒక తప్పు క్షమించబడుతుంది.", 'ta': "மெதுவான ஒளி, 4 பட்டைகள், ஒரு தவறு மன்னிக்கப்படும்.", 'pa': "ਹੌਲੀ ਰੌਸ਼ਨੀ, 4 ਪੈਡ, ਇੱਕ ਗਲਤੀ ਮਾਫ਼।", 'bho': "धीमा रोसनी, 4 पैड, एगो गलती माफ।", 'mr': "मंद दिवे, 4 पॅड, एक चूक माफ.", 'sa': "मन्दप्रकाशः, 4 फलकानि, एकः दोषः क्षम्यः।"},
  'memory_boost.simon.desc.medium': {'en': "Classic speed, 4 pads.", 'hi': "सामान्य रफ़्तार, 4 पैड।", 'hinglish': "Classic speed, 4 pads.", 'te': "సాధారణ వేగం, 4 ప్యాడ్లు.", 'ta': "வழக்கமான வேகம், 4 பட்டைகள்.", 'pa': "ਆਮ ਰਫ਼ਤਾਰ, 4 ਪੈਡ।", 'bho': "सामान्य रफ्तार, 4 पैड।", 'mr': "सामान्य वेग, 4 पॅड.", 'sa': "सामान्यवेगः, 4 फलकानि।"},
  'memory_boost.simon.desc.hard': {'en': "Fast lights, 4 pads.", 'hi': "तेज़ रोशनी, 4 पैड।", 'hinglish': "Fast lights, 4 pads.", 'te': "వేగమైన లైట్లు, 4 ప్యాడ్లు.", 'ta': "வேகமான ஒளி, 4 பட்டைகள்.", 'pa': "ਤੇਜ਼ ਰੌਸ਼ਨੀ, 4 ਪੈਡ।", 'bho': "तेज रोसनी, 4 पैड।", 'mr': "जलद दिवे, 4 पॅड.", 'sa': "शीघ्रप्रकाशः, 4 फलकानि।"},
  'memory_boost.simon.desc.extreme': {'en': "Blazing speed with 6 pads.", 'hi': "6 पैड के साथ बिजली जैसी रफ़्तार।", 'hinglish': "6 pads ke saath super fast speed.", 'te': "6 ప్యాడ్లతో మెరుపు వేగం.", 'ta': "6 பட்டைகளுடன் மின்னல் வேகம்.", 'pa': "6 ਪੈਡਾਂ ਨਾਲ ਬਿਜਲੀ ਵਰਗੀ ਰਫ਼ਤਾਰ।", 'bho': "6 पैड के साथे बिजली नियर रफ्तार।", 'mr': "6 पॅडसह विजेसारखा वेग.", 'sa': "6 फलकैः सह विद्युद्वेगः।"},
  'memory_boost.simon.streak_value': {'en': "Streak: {n}", 'hi': "लगातार: {n}", 'hinglish': "Streak: {n}", 'te': "వరుస: {n}", 'ta': "தொடர்: {n}", 'pa': "ਲੜੀ: {n}", 'bho': "लगातार: {n}", 'mr': "सलग: {n}", 'sa': "अनुक्रमः: {n}"},
  'memory_boost.simon.streak_chip': {'en': "Streak {n}", 'hi': "लगातार {n}", 'hinglish': "Streak {n}", 'te': "వరుస {n}", 'ta': "தொடர் {n}", 'pa': "ਲੜੀ {n}", 'bho': "लगातार {n}", 'mr': "सलग {n}", 'sa': "अनुक्रमः {n}"},
  'memory_boost.simon.status.idle': {'en': "Watch the pattern, then repeat it", 'hi': "पैटर्न देखें, फिर दोहराएं", 'hinglish': "Pattern dekho, phir repeat karo", 'te': "నమూనా చూడు, తర్వాత మళ్లీ చేయి", 'ta': "வரிசையைப் பார், பிறகு திரும்பச் செய்", 'pa': "ਪੈਟਰਨ ਦੇਖੋ, ਫਿਰ ਦੁਹਰਾਓ", 'bho': "पैटर्न देखीं, फेर दोहराईं", 'mr': "क्रम पाहा, मग पुन्हा करा", 'sa': "क्रमं पश्यत, ततः पुनः कुरुत"},
  'memory_boost.simon.status.watching': {'en': "Watch...", 'hi': "देखें...", 'hinglish': "Dekho...", 'te': "చూడు...", 'ta': "பார்...", 'pa': "ਦੇਖੋ...", 'bho': "देखीं...", 'mr': "पाहा...", 'sa': "पश्यत..."},
  'memory_boost.simon.status.input': {'en': "Your turn!", 'hi': "आपकी बारी!", 'hinglish': "Tumhari baari!", 'te': "నీ వంతు!", 'ta': "உன் முறை!", 'pa': "ਤੁਹਾਡੀ ਵਾਰੀ!", 'bho': "रउआ बारी!", 'mr': "तुमची पाळी!", 'sa': "भवतः वारः!"},

  // ---- Number Memory
  'memory_boost.number.heading': {'en': "Memorize the number, then type it. Each round adds a digit. Pick a difficulty.", 'hi': "नंबर याद करें, फिर टाइप करें। हर राउंड एक अंक बढ़ता है। कठिनाई चुनें।", 'hinglish': "Number yaad karo, phir type karo. Har round ek digit badhta hai. Difficulty chuno.", 'te': "సంఖ్యను గుర్తుంచుకుని టైప్ చేయి. ప్రతి రౌండ్‌కు ఒక అంకె పెరుగుతుంది. కష్టస్థాయి ఎంచుకో.", 'ta': "எண்ணை நினைவில் வைத்துத் தட்டச்சு செய். ஒவ்வொரு சுற்றிலும் ஒரு இலக்கம் கூடும். கடினநிலையைத் தேர்வு செய்.", 'pa': "ਨੰਬਰ ਯਾਦ ਕਰੋ, ਫਿਰ ਟਾਈਪ ਕਰੋ। ਹਰ ਰਾਊਂਡ ਇੱਕ ਅੰਕ ਵਧਦਾ ਹੈ। ਮੁਸ਼ਕਲ ਚੁਣੋ।", 'bho': "नंबर याद करीं, फेर टाइप करीं। हर राउंड में एगो अंक बढ़ेला। कठिनाई चुनीं।", 'mr': "संख्या लक्षात ठेवा, मग टाइप करा. प्रत्येक फेरीत एक अंक वाढतो. काठिण्य निवडा.", 'sa': "संख्यां स्मरत, ततः लिखत। प्रतिचरणम् एकः अङ्कः वर्धते। काठिन्यं चिनुत।"},
  'memory_boost.number.desc': {'en': "Starts at {digits}, {sec} to look, {lives}.", 'hi': "{digits} से शुरू, देखने को {sec}, {lives}।", 'hinglish': "{digits} se start, dekhne ko {sec}, {lives}.", 'te': "{digits}తో మొదలు, చూడటానికి {sec}, {lives}.", 'ta': "{digits}இல் தொடக்கம், பார்க்க {sec}, {lives}.", 'pa': "{digits} ਤੋਂ ਸ਼ੁਰੂ, ਦੇਖਣ ਲਈ {sec}, {lives}।", 'bho': "{digits} से शुरू, देखे खातिर {sec}, {lives}।", 'mr': "{digits} पासून सुरुवात, पाहण्यासाठी {sec}, {lives}.", 'sa': "{digits} तः आरम्भः, दर्शनाय {sec}, {lives}।"},
  'memory_boost.number.digit_one': {'en': "{n} digit", 'hi': "{n} अंक", 'hinglish': "{n} digit", 'te': "{n} అంకె", 'ta': "{n} இலக்கம்", 'pa': "{n} ਅੰਕ", 'bho': "{n} अंक", 'mr': "{n} अंक", 'sa': "{n} अङ्कः"},
  'memory_boost.number.digit_many': {'en': "{n} digits", 'hi': "{n} अंक", 'hinglish': "{n} digits", 'te': "{n} అంకెలు", 'ta': "{n} இலக்கங்கள்", 'pa': "{n} ਅੰਕ", 'bho': "{n} अंक", 'mr': "{n} अंक", 'sa': "{n} अङ्काः"},
  'memory_boost.number.life_one': {'en': "{n} life", 'hi': "{n} जीवन", 'hinglish': "{n} life", 'te': "{n} ప్రాణం", 'ta': "{n} உயிர்", 'pa': "{n} ਜਾਨ", 'bho': "{n} जान", 'mr': "{n} जीव", 'sa': "{n} प्राणः"},
  'memory_boost.number.life_many': {'en': "{n} lives", 'hi': "{n} जीवन", 'hinglish': "{n} lives", 'te': "{n} ప్రాణాలు", 'ta': "{n} உயிர்கள்", 'pa': "{n} ਜਾਨਾਂ", 'bho': "{n} जान", 'mr': "{n} जीव", 'sa': "{n} प्राणाः"},
  'memory_boost.number.rounds_cleared': {'en': "Rounds cleared: {n}", 'hi': "पार किए राउंड: {n}", 'hinglish': "Rounds clear: {n}", 'te': "పూర్తైన రౌండ్లు: {n}", 'ta': "முடித்த சுற்றுகள்: {n}", 'pa': "ਪਾਰ ਕੀਤੇ ਰਾਊਂਡ: {n}", 'bho': "पार कइल राउंड: {n}", 'mr': "पार केलेल्या फेऱ्या: {n}", 'sa': "उत्तीर्णचरणानि: {n}"},
  'memory_boost.number.what_was': {'en': "What was the number?", 'hi': "नंबर क्या था?", 'hinglish': "Number kya tha?", 'te': "సంఖ్య ఏమిటి?", 'ta': "எண் என்ன?", 'pa': "ਨੰਬਰ ਕੀ ਸੀ?", 'bho': "नंबर का रहे?", 'mr': "संख्या कोणती होती?", 'sa': "संख्या का आसीत्?"},
  'memory_boost.number.correct': {'en': "Correct!", 'hi': "सही!", 'hinglish': "Sahi!", 'te': "సరైనది!", 'ta': "சரி!", 'pa': "ਸਹੀ!", 'bho': "सही!", 'mr': "बरोबर!", 'sa': "सम्यक्!"},
  'memory_boost.number.it_was': {'en': "It was {n}", 'hi': "यह {n} था", 'hinglish': "Ye {n} tha", 'te': "అది {n}", 'ta': "அது {n}", 'pa': "ਇਹ {n} ਸੀ", 'bho': "ई {n} रहे", 'mr': "ती {n} होती", 'sa': "सा {n} आसीत्"},
  'memory_boost.number.you_typed': {'en': "You typed {n}", 'hi': "आपने {n} टाइप किया", 'hinglish': "Tumne {n} type kiya", 'te': "నువ్వు {n} టైప్ చేశావు", 'ta': "நீ {n} தட்டச்சு செய்தாய்", 'pa': "ਤੁਸੀਂ {n} ਟਾਈਪ ਕੀਤਾ", 'bho': "रउआ {n} टाइप कइनी", 'mr': "तुम्ही {n} टाइप केले", 'sa': "भवता {n} लिखितम्"},
  'memory_boost.number.round_n': {'en': "Round {n}", 'hi': "राउंड {n}", 'hinglish': "Round {n}", 'te': "రౌండ్ {n}", 'ta': "சுற்று {n}", 'pa': "ਰਾਊਂਡ {n}", 'bho': "राउंड {n}", 'mr': "फेरी {n}", 'sa': "चरणम् {n}"},
};
