// Curated middlegame start positions for the "Mid-game" start option.
// Each one is a well-known opening line played out for ~10-13 moves: material
// is level, both sides have play, and the side to move varies. All positions
// were generated by playing the moves through [Position] and are verified in
// test/chess/chess_positions_test.dart.

import 'dart:math' as math;

class MidgamePosition {
  const MidgamePosition(this.name, this.fen);

  /// Opening name shown on the board header (a proper name, not translated).
  final String name;
  final String fen;
}

const List<MidgamePosition> midgamePositions = [
  MidgamePosition("Italian Game", 'r1bq1rk1/bpp2pp1/p1np1n1p/4p3/P1B1P3/2PP1N1P/1P1N1PP1/R1BQR1K1 b - - 1 10'),
  MidgamePosition("Italian Game, Giuoco Pianissimo", 'r1bqr1k1/bpp2pp1/p1np1n1p/4p3/PPB1P3/2PP1N1P/3N1PP1/R1BQR1K1 b - - 0 11'),
  MidgamePosition("Two Knights Defence", 'r1bq1rk1/1p2bppp/p2p1n2/n1p1p3/B3P3/2PP1N2/PP1N1PPP/R1BQR1K1 b - - 1 10'),
  MidgamePosition("Ruy Lopez, Closed", 'r1b2rk1/2q1bppp/p2p1n2/npp1p3/3PP3/2P2N1P/PPB2PP1/RNBQR1K1 w - - 1 12'),
  MidgamePosition("Ruy Lopez, Berlin", 'r1bq1rk1/ppp2ppp/1b1p1nn1/4p3/3PP3/2PB1N1P/PP1N1PP1/R1BQ1RK1 b - - 4 10'),
  MidgamePosition("Ruy Lopez, Breyer", 'r2qr1k1/1bpnbppp/p2p1n2/1p2p3/3PP3/2P2N1P/PPBN1PP1/R1BQR1K1 w - - 5 13'),
  MidgamePosition("Scotch Game", '2kr1b1r/p1ppqppp/b1p5/3nP3/2P5/1P4P1/P3QP1P/RNB1KB1R b KQ - 0 10'),
  MidgamePosition("Petroff Defence", 'r2q1rk1/ppp1bppp/8/3p1b2/1nPPn3/2N2N2/PP2BPPP/R1BQ1RK1 w - - 5 11'),
  MidgamePosition("Sicilian Najdorf", 'r2q1rk1/3nbppp/p2pbn2/1p2p3/4P1P1/1NN1BP2/PPPQ3P/2KR1B1R w - - 0 12'),
  MidgamePosition("Sicilian Najdorf, Classical", 'r2q1rk1/1p1nbppp/p2pbn2/4p3/P3P3/1NN1B3/1PPQBPPP/R4RK1 b - - 0 11'),
  MidgamePosition("Sicilian Dragon", '2rq1rk1/pp1bppbp/3p1np1/4n3/3NP3/1BN1BP2/PPPQ2PP/2KR3R w - - 9 12'),
  MidgamePosition("Sicilian Scheveningen", 'r1b2rk1/1pq1bppp/p1nppn2/8/P2NPP2/2N1B3/1PP1B1PP/R2Q1R1K b - - 0 11'),
  MidgamePosition("Sicilian Sveshnikov", 'r1bqk2r/5pbp/p1np4/1p1Npp2/4P3/N1P5/PP3PPP/R2QKB1R w KQkq - 1 12'),
  MidgamePosition("Sicilian Taimanov", 'r1b1k2r/1pq2ppp/p2ppn2/2b1n3/3NPP2/2NBB2P/PPP3P1/R2Q1R1K b kq - 0 11'),
  MidgamePosition("Sicilian, Alapin", 'r3kb1r/pp1qpppp/1nn5/1B6/3P4/8/PP3PPP/RNBQK2R w KQkq - 0 11'),
  MidgamePosition("French, Winawer", 'r1bq2k1/pp2n1pp/2n1pr2/2pp2B1/3P2Q1/P1PB1N2/2P2PPP/R3K2R b KQ - 1 11'),
  MidgamePosition("French, Classical", 'r1bq1rk1/p2nbppp/1pn1p3/2ppP3/3P1P2/2N1BN2/PPPQB1PP/R4RK1 b - - 1 10'),
  MidgamePosition("French, Tarrasch", 'r1bq1rk1/pp4pp/2nbpn2/3p4/3P4/3B1N2/PP2NPPP/R1BQ1RK1 w - - 4 12'),
  MidgamePosition("French, Advance", 'r1n1kb1r/pp1b1ppp/1q2p3/n2pP3/2pP4/P1P2N2/1P1NBPPP/1RBQ1RK1 w kq - 8 11'),
  MidgamePosition("Caro-Kann, Classical", 'r2qk2r/pp1nbpp1/2p1pn1p/7P/3P4/3Q1NN1/PPPB1PP1/2KR3R w kq - 4 13'),
  MidgamePosition("Caro-Kann, Advance", 'r2qk2r/pp1nbppp/4p3/2pnPb2/2NP4/4BN2/PP2BPPP/R2Q1RK1 w kq - 1 11'),
  MidgamePosition("Scandinavian Defence", 'r3k2r/pp1n1ppp/2p1pn2/q4b2/1bBP4/2N2N2/PPPBQPPP/1K1R3R b kq - 5 10'),
  MidgamePosition("Pirc Defence", 'r1b2rk1/pp1nqpbp/2p2np1/4p3/P3P3/2N1BN1P/1PP1BPP1/R2Q1RK1 w - - 2 11'),
  MidgamePosition("Queen's Gambit Declined", 'rn3rk1/pbp2pp1/1p1q1b1p/3p4/3P4/2N1PN2/PP2BPPP/R2Q1RK1 w - - 2 12'),
  MidgamePosition("QGD, Orthodox", 'r1b2rk1/pp1nqppp/2p1p3/3n4/2BP4/2N1PN2/PP3PPP/2RQ1RK1 b - - 1 11'),
  MidgamePosition("Queen's Gambit Accepted", 'rn2k2r/1b3ppp/p3pn2/1pb5/P7/4PN2/1P2BPPP/RNBR1K2 b kq - 0 11'),
  MidgamePosition("Slav Defence", 'r2q1rk1/pp1n1ppp/2p1pnb1/8/Pb1PP3/2NB1N2/1P2QPPP/R1B2RK1 b - - 2 11'),
  MidgamePosition("Semi-Slav, Meran", 'r3kb1r/1bqn1ppp/p3pn2/1ppP4/4P3/2NB1N2/PP3PPP/R1BQ1RK1 w kq - 1 12'),
  MidgamePosition("King's Indian Defence", 'r1bq1rk1/ppp1n1bp/3p1np1/3Ppp2/2P1P3/2NN4/PP1BBPPP/R2Q1RK1 w - - 2 12'),
  MidgamePosition("King's Indian, Sämisch", 'r1bq1rk1/ppp3bp/3p1np1/3Ppp1n/2P1P3/2NBBP2/PP1Q2PP/2KR2NR w - - 4 11'),
  MidgamePosition("Grünfeld Defence", 'r1b2rk1/pp2ppbp/2n3p1/8/3PP3/4BN2/P2K1PPP/2R2B1R w - - 1 13'),
  MidgamePosition("Nimzo-Indian Defence", 'r1b2rk1/ppq2ppp/2n2n2/2p1p3/3P4/P1PBPN2/5PPP/R1BQ1RK1 w - - 0 12'),
  MidgamePosition("Nimzo-Indian, Classical", 'r2q1rk1/pb1n1ppp/1p1ppn2/2p3B1/2PP4/P1QBPP2/1P2N1PP/R3K2R b KQ - 1 11'),
  MidgamePosition("Queen's Indian Defence", 'r2q1rk1/p2nbppp/bpp1pn2/3p4/2PP4/1PB2NP1/P2NPPBP/R2QR1K1 b - - 5 11'),
  MidgamePosition("Catalan Opening", 'r2q1rk1/1pp1bppp/n1b1pn2/p5B1/P1QP4/2N2NP1/1P2PPBP/R4RK1 w - - 2 12'),
  MidgamePosition("Benoni Defence", 'r1bqr1k1/ppn2pbp/3p1np1/2pP4/P3P3/2N2P2/1P1NB1PP/R1BQ1RK1 b - - 0 12'),
  MidgamePosition("Dutch, Stonewall", 'rn2brk1/pp2q1pp/2pbpn2/3pNp2/2PP4/1P4P1/PB1NPPBP/R2Q1RK1 w - - 7 11'),
  MidgamePosition("London System", 'r2q1rk1/pb2nppp/1p1bpn2/2ppN3/3P1P2/2PBP1B1/PP1N2PP/R2Q1RK1 b - - 2 11'),
  MidgamePosition("London vs King's Indian", 'r1b1r1k1/pppnqpbp/3p1np1/4p3/2PP4/2N1PN1P/PP2BPPB/R2Q1RK1 w - - 4 11'),
  MidgamePosition("Colle System", 'r1b2rk1/ppq2ppp/2nbpn2/3p4/4P3/2PB1N2/PP1NQPPP/R1B2RK1 w - - 3 11'),
  MidgamePosition("English Opening", 'r2q1rk1/ppp1b1pp/1nn1bp2/4p3/1P6/P1NP1NP1/4PPBP/R1BQ1RK1 w - - 0 11'),
  MidgamePosition("English, Symmetrical", 'r1bq1rk1/1p2ppbp/p2p1np1/8/2P5/2NQ2P1/PP1BPPBP/R4RK1 b - - 1 11'),
  MidgamePosition("Réti Opening", 'r2q1rk1/pp1n1ppp/2p2n2/2b1p2b/4P3/5NPP/PPPN1PB1/R1B1QRK1 w - - 3 11'),
  MidgamePosition("King's Indian Attack", 'r1bq1rk1/3nbppp/2n1p3/ppppP3/7P/3P1NP1/PPP2PB1/R1BQRNK1 b - - 0 11'),
  MidgamePosition("Vienna Game", 'r1bq1rk1/ppp2pp1/3p1n1p/4p3/2P1P3/1P1P1N2/2P2PPP/R1BQ1RK1 w - - 0 11'),
  MidgamePosition("Bishop's Opening", 'r1bqr1k1/pp3pp1/1npb1n1p/3Pp3/8/1BNP1N1P/PPP2PP1/R1BQR1K1 w - - 1 11'),
];

/// A random curated middlegame position.
MidgamePosition randomMidgame([math.Random? rng]) => midgamePositions[(rng ?? math.Random()).nextInt(midgamePositions.length)];
